apiVersion: v2
appVersion: 0.1.0
name: opencost
description: OpenCost is a vendor-neutral open source project for measuring and allocating infrastructure and container costs in Kubernetes environments.
home: https://github.com/giantswarm/opencost

# If you have an icon/logo, you should add it to https://github.com/giantswarm/web-assets
# and set the final URL as a value here and uncomment.
# icon: https://s.giantswarm.io/app-icons/example/1/light.svg

# sources:
# - https://github.com/opencost/opencost
sources:
  - "https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack"
  - "https://github.com/opencost/opencost-helm-chart/tree/main/charts/opencost"

version: "[[ .Version ]]"
annotations:
  application.giantswarm.io/team: phoenix

dependencies:
  - name: prometheus
    version: "22.6.*"
    repository: https://prometheus-community.github.io/helm-charts
  - name: opencost
    version: "1.16.*"
    repository: https://opencost.github.io/opencost-helm-chart
