{{- if and (eq (int .Capabilities.KubeVersion.Major) 1) (le (int .Capabilities.KubeVersion.Minor) 24) }}
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: opencost
spec:
  allowPrivilegeEscalation: false
  hostNetwork: true
  hostPID: true
  allowedHostPaths:
    - pathPrefix: /proc
      readOnly: true
    - pathPrefix: /sys
      readOnly: true
    - pathPrefix: /
      readOnly: true
  hostPorts:
  - min: 9100
    max: 9100
  fsGroup:
    ranges:
    - max: 65535
      min: 0
    rule: MustRunAs
  runAsUser:
    ranges:
    - max: 65535
      min: 0
    rule: MustRunAs
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    ranges:
    - max: 65535
      min: 0
    rule: MustRunAs
  volumes:
  - secret
  - configMap
  - projected
  - emptyDir
  - persistentVolumeClaim
  - hostPath
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: opencost
rules:
- apiGroups: ['policy']
  resources: ['podsecuritypolicies']
  verbs:     ['use']
  resourceNames:
  - opencost
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: opencost
roleRef:
  kind: Role
  name: opencost
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: {{ .Values.opencost.serviceAccount.name | default "opencost" }}
- kind: ServiceAccount
  name: opencost-prometheus-server
- kind: ServiceAccount
  name: opencost-prometheus-node-exporter
{{- end }}
