{{- if and (eq .Capabilities.KubeVersion.Major 1) (lt .Capabilities.KubeVersion.Major 25) -}}
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: opencost
spec:
  allowPrivilegeEscalation: false
  fsGroup:
    ranges:
    - max: 65535
      min: 0
    rule: MustRunAs
  runAsUser:
    ranges:
    - max: 65535
      min: 0
    rule: MustRunAs
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    ranges:
    - max: 65535
      min: 0
    rule: MustRunAs
  volumes:
  - secret
  - configMap
  - projected
  - emptyDir
  - persistentVolumeClaim
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: opencost
rules:
- apiGroups: ['policy']
  resources: ['podsecuritypolicies']
  verbs:     ['use']
  resourceNames:
  - opencost
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: opencost
roleRef:
  kind: Role
  name: opencost
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: opencost
{{- end }}
