apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.opencost.serviceAccount.name | default "opencost" }}
  labels: {{- include "opencost.labels" . | nindent 4 }}
  annotations:
  {{- include "giantswarm.irsa.annotation" . | nindent 4 }}
  {{- with .Values.opencost.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}  
automountServiceAccountToken: {{ .Values.opencost.serviceAccount.automountServiceAccountToken }}