apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: opencost-ui
spec:
  resourcePolicy:
    containerPolicies:
    - containerName: opencost-ui
      controlledValues: RequestsAndLimits
      minAllowed:
        cpu: 100m
        memory: 256mi
      mode: Auto
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: opencost
  updatePolicy:
    updateMode: Auto
